### ISSUE TITLE
PyLadies Global Council Election Comms Strategy 2020

### ISSUE THREAD

**Issue by lorenanicole** [pyladies/project-communications#24]
# Overview

Tracking issue to track the PyLadies Global Council Election Comms Strategy 2020.

*What is the background for this work?*

PyLadies is hosting an election for the inaugural 2020 PyLadies Global Council. The election will be a public election and nomination as decided [here](https://github.com/pyladies/global-organizing/issues/50). The proposed timeline for the election is [here](https://github.com/pyladies/global-organizing/issues/46).

## Scope of Work

*Registering PyLadies Members*
To prep for the election, the Global interim group (led by @lorenanicole) needs to collect members data so we can contact them regarding the election. Work is tracked in GitHub issue [here](https://github.com/pyladies/global-organizing/issues/54).

*Comms Strategy*

We will need, at least, the following content created and published with these target dates:

- [X] [MAR 7 2020] Announcement for registering to be a PyLadies member
   - Published on: social media, PyLadies blog, slack, Python Software Foundation blog
- [ ] [APR 15 2020] Announcement for the general election (similar to Python Software Foundation Board of Direction announcement with timeline)
   - Published on: social media, PyLadies blog, slack, Python Software Foundation blog
- [ ] [JUNE 2020] Announcement of results of election
   - Published on: social media, PyLadies blog, slack, Python Software Foundation blog

*Who is coordinating/working*
*PLEASE FILL IN FOR WHO IS HELPING FROM PROJECT COMMS*
- @lorenanicole is coordinating election
- @deboraazevedo is coordinating translation
- @AbigailMesrenyameDogbe is coordinating publishing content

## Deliverables

Non-Publishing Work:
- [ ] Feedback on questions we collect for [PyLadies member database](https://github.com/pyladies/global-organizing/issues/54)
- [ ] Review and familiarize with [PyLadies Global Council election timeline](https://github.com/pyladies/global-organizing/issues/46)

Publishing calendar:
- [ ] Mar 1 2020 member registration announcement:
     - [ ] Approved copy: https://docs.google.com/document/d/1Lt7OmbjvQCybfcQ5sclGW2pbrr1zAzGM-t5vlLmMtdw/edit?ts=5e4d62b8
     - [ ] Translated 
     - [ ] Published 
- [ ] Mar 15 2020 general election announcement:
     - [ ] Approved copy 
     - [ ] Translated 
     - [ ] Published 
- [ ] Apr/May 2020 general election results announcement:
     - [ ] Approved copy 
     - [ ] Translated 
     - [ ] Published

**Comment by Caaddss** [comment]
Sure!! Its good saw this [issue](https://github.com/pyladies/global-organizing/issues/58#issue-551167131) too

**Comment by Marie-L** [comment]
@lorenanicole, thanks for creating this issue! There's quite a lot in here so I think that it would be best to turn this into an epic and separate it into separate issues, what do you think ?

**Comment by lorenanicole** [comment]
@Marie-L however you all see fit! That said, I do love a tracker issue since we can use it as the final ✔️ list for ensuring all units of work done. But if you want to move into a project board, sure. Can we actually use a GitHub project board then? Looking for Google Docs can be hard to find ergo making this work not transparent .

**Comment by Caaddss** [comment]
@lorenanicole  Im confusing about database and procedure to registration...will be like PSF members? I read the issues but isnt clean to me the process

**Comment by Marie-L** [comment]
@lorenanicole ok great! Yeah I'll add the issues to our current project board (unless you would like me to create a separate one for this strategy).

@Caaddss once the issues are broken down into smaller ones then we can clarify the details of each sub category and the fulfilment criteria

**Comment by lorenanicole** [comment]
We've started writing the content here, thanks @AbigailMesrenyameDogbe for tstarting this https://docs.google.com/document/d/1Lt7OmbjvQCybfcQ5sclGW2pbrr1zAzGM-t5vlLmMtdw/edit?ts=5e4d62b8!

**Comment by Marie-L** [comment]
hey @lorenanicole, regarding _[FEB 15 2020] Announcement for registering to be a PyLadies member_ how can a person register to be a pyladies member, what's the current process ? We've missed this deadline, so please let me know asap so that we can make the announcement maybe this week

**Comment by Marie-L** [comment]
@lorenanicole @Caaddss @AbigailMesrenyameDogbe I think that the announcements should consist of a basic graphics type ad, what do you all think ? or is a text post enough? Also @lorenanicole, who is in charge of the pyladies social media accounts and psf blog?

**Comment by Marie-L** [comment]
**Epic**  _(will be fleshed out in the coming days)_: 
- [ ] Election Comms Strategy : advert artwork & copy #33
- [ ] Election Comms Strategy : Non-publishing work #34 
- [ ] Election Comms Strategy : member registration announcement #35 
- [ ] Election Comms Strategy : election announcement #36 
- [ ] Election Comms Strategy : election results announcement #37

**Comment by lorenanicole** [comment]
@Marie-L the first blog post announcement to do the pyladies member registration is in a PR on the pyladies website, @pyladies/tech-and-infra-admins are the folks who have permissions for that repo.

**Comment by Marie-L** [comment]
@lorenanicole , @AbigailDogbe, @Caaddss [PR for social media announcement](https://github.com/pyladies/project-communications/pull/38)

**Comment by Marie-L** [comment]
I'll close this issue as the work has now been completed .
