### ISSUE TITLE
Research PyLadies & other programming websites

### ISSUE THREAD

**Issue by Marie-L** [pyladies/project-communications#3]
# Plan
_Each task has been separated into issues, please select one and assign yourself_
- [x] #5 Make a list of the current contributors / editors of the blog
- [x] #6 find out whether processes for contributing have been documented
- [x] #7 Write use cases 
- [ ] #8 write PyLadies blog case study
- [x] #9 Search for a few blogs which have similar use cases
- [ ] #10 Write case studies for each 
- [ ] #11 List action points which are a direct result of the research

**Comment by lorenanicole** [comment]
@Marie-L I love this! Do you plan on doing all this research yourself? Or would you like help on specific line items? For example you can assign names for each bullet in your list ... additionally do you have a deadline for when these items should be done? 

My proposal would be you can use this as a tracking issue and each bullet point on your list can be a GitHub issue where you present the findings. Additionally those assigned on the research are those that want to help!

Thoughts?

**Comment by lorenanicole** [comment]
Some feedback on the items ...

> [ ]  Write use cases

What do you mean by use cases for the blog? Do you mean for rebuilding the blog website?

**Comment by Marie-L** [comment]
Hey @lorenanicole, Thank you for your feedback ! 

It would be great to get some help, if anyone is interested but if not then I don't mind doing it alone. So yeah, if people volunteer their time then I would be happy to assign each person to each bullet point, that's a great idea !

By use cases I mean for example _"The user needs to access the PyLadies google map (on the locations page) to find their closest chapter "_  but I also think that writing user stories could be useful too. Does that answer your question ?

With regard to a deadline, again that depends on how many people would like to get involved and also how quickly we would like to start rebuilding the blog.  

When you have time please let me know what you think.

**Comment by Caaddss** [comment]
@Marie-L continuous your example...do you think something like find closest meetup too??

So I can help you, but I need understand better your idea...maybe follow @lorenanicole  about open one issue to each point

**Comment by Marie-L** [comment]
Hey @Caaddss, that's a great idea !

Ok sure, I'll create an epic separating each point by issue hopefully before the end of the week. Thank you for your feedback !

**Comment by Caaddss** [comment]
@Marie-L Want help opening issues?

I can open, based in this issue and you edit after with some details... what do you think?

**Comment by Marie-L** [comment]
Thanks for the offer @Caaddss, but don't worry 😉. I'll do it quickly but please feel free to edit etc

**Comment by Marie-L** [comment]
@Caaddss @lorenanicole I realised after that an epic can only be created using the zenHub plugin, so I created each issue and added the links manually to the first comment

**Comment by Caaddss** [comment]
@Marie-L AWESOME!!! thank you!!!

**Comment by Marie-L** [comment]
@Caaddss no problem 😊!

**Comment by lorenanicole** [comment]
@Marie-L there are Project boards in GitHub! Here you go: https://github.com/pyladies/project-communications/projects.

**Comment by Marie-L** [comment]
Thanks @lorenanicole , I'll create another here and delete the previous one

**Comment by voru588** [comment]
Ok, I am not sure where I should ask my question. 
Why do we need to divide the blog into chapters? I think that the global news will be interesting for everyone. Plus, it will be easier to find contributors globally.
However, we can have "Local chapter news" as a separate section for local meet-ups and the latest news as they will be less frequent than in the main section.

**Comment by lorenanicole** [comment]
@voru588 is there somewhere that a proposal exists for a local vs chapter news section? I don't readily see it on this issue.
